name: Convert HTML to PDF and push to main

permissions:
  contents: write

on:
  push:
    branches:
      # - testing-ci2 # Delete me after testing is over
      - main
    # paths:
    #     - docs/src/**
    #     - docs/make.jl
    # Uncomment these lines after the test is over
jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "gh-pages"

      - name: html to pdf
        uses: markwilson/html2pdf@v1.1
        with:
          htmlPath: dev/info/index.html
          pdfName: temp
          # This results in ./dist/temp.pdf
          # See https://github.com/markwilson/html2pdf/blob/master/entrypoint.sh
      - name: Commit and push PDF to main
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git fetch
          git checkout main
          cp dist/temp.pdf README_html.pdf
          git add README_html.pdf
          git commit -m "Update README_html.pdf"
        shell: bash
      - name: Push pdf
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
# CHECKPOINT: Basically, this CI successfully build PDF. However, "chrome-headless-render-pdf" does not intrinsically contain CJK characters (since it is big); you have to install the font first.
