name: Convert HTML to PDF and push to main

on:
  push:
    branches:
      - gh-pages
      - testing-ci2
    # paths:
    #   - ./docs
jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "gh-pages"
      - name: html to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./dev/index.html
          outputFile: ./README.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
      - name: Commit and push PDF to main
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git checkout main
          mv README.pdf docs/README.pdf
          git add docs/README.pdf
          git commit -m "Update README.pdf"
        shell: bash
      - name: Push pdf
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
