on:
  push:
    branches:
      - gh-pages
    # paths:
    #   - ./docs
jobs:
  copy-file:
    runs-on: ubuntu-latest
    # environment: github-pages # you have to already have this environment in this repo
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "gh-pages"
      - name: html to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./dev/index.html
          outputFile: ./README.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
