name: Convert HTML to PDF and push to main

permissions:
  contents: write

on:
  push:
    branches:
      - testing-ci2 # Delete me after testing is over
      - main
    # paths:
    #     - docs/src/**
    #     - docs/make.jl
    # Uncomment these lines after the test is over
jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "gh-pages"

      - name: html to pdf
        uses: markwilson/html2pdf@v1.0
        with:
          htmlPath: ./dev/info/index.html
          pdfName: ./temp.pdf

      - name: Commit and push PDF to main
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git fetch
          git checkout main
          mv temp.pdf docs/info.pdf
          git add docs/info.pdf
          git commit -m "Update info.pdf"
        shell: bash
      - name: Push pdf
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
