name: Convert HTML to PDF and push to main

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build pdf and html
        uses: baileyjm02/markdown-to-pdf@v1 # https://github.com/BaileyJM02/markdown-to-pdf#markdown-to-pdf
        with:
          input_path: ./docs/src/info.md
          output_dir: ./
          # images_dir: docs/images
          # # for example <img src="./images/file-name.png">
          # image_import: ./images
          # # Default is true, can set to false to only get PDF files
          build_html: true
          build_pdf: true

      - name: Commit and push PDF to main
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git fetch origin
          git checkout main
          mv ./info.pdf ./README.pdf
          git add README.pdf
          git commit -m "Update README.pdf"
        shell: bash
        # KEYNOTE: If the push action that triggered this workflow is not limited to branch `main`,
        # `git checkout main` is required since you are going to push it to main in the next step.
        # `git fetch origin (main)` is also required otherwise `git checkout main` might fail.
      - name: Push pdf
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
