name: Convert HTML to PDF and push to main

on:
  push:
    branches:
      - testing-ci2
    # paths:
    #   - ./docs
jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "main"

      - name: html to pdf
        uses: misaelnieto/web_to_pdf_action@master
        with:
          webPageURL: https://okatsn.github.io/BasicProgramming-NCUES-112-1/dev/info/
          outputFile: ./docs/info.pdf
          usePuppeteer: true
          useScreen: true
          pdfOptions: '{"format": "Letter", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

      - name: Commit and push PDF to main
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add docs/info.pdf
          git commit -m "Update info.pdf"
        shell: bash
      - name: Push pdf
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
